FROM alpine:3.18.0 AS builder
RUN apk add dotnet7-sdk
COPY . /tmp/builder
RUN dotnet publish "/tmp/builder" --configuration "Release" --no-self-contained --output "/tmp/builder/bin/publish"

FROM alpine:3.18.0
RUN apk add aspnetcore7-runtime
COPY --from=builder /tmp/builder/bin/publish /opt/hello
ENTRYPOINT ["dotnet", "/opt/hello/Martin.Hello.dll"]
